export enum orderStatus {
  Completed = "Completed",
  Inprocess = "Inprocess",
  Cancelled = "Cancelled",
  New_Order = "New Order",
}

export interface OrderTableData {
  Order_ID: string;
  Customer_Name: string;
  Date: string;
  Amount: string;
  Payment_Type: string;
  Status: orderStatus;
}

export const orderTableData: OrderTableData[] = [
  {
    Order_ID: "19668275",
    Customer_Name: "Nicole Shaffer",
    Date: "May 14, 2025",
    Amount: "$229",
    Payment_Type: "Bank Transfer",
    Status: orderStatus.Completed,
  },
  {
    Order_ID: "41243275",
    Customer_Name: "Steven Patterson",
    Date: "Jan 08, 2025",
    Amount: "$107",
    Payment_Type: "Bank Transfer",
    Status: orderStatus.New_Order,
  },
  {
    Order_ID: "46095439",
    Customer_Name: "Shaun Chung",
    Date: "Apr 05, 2025",
    Amount: "$329",
    Payment_Type: "Credit Card",
    Status: orderStatus.Cancelled,
  },
  {
    Order_ID: "16112056",
    Customer_Name: "Victoria Garcia",
    Date: "Nov 13, 2024",
    Amount: "$394",
    Payment_Type: "PayPal",
    Status: orderStatus.Inprocess,
  },
  {
    Order_ID: "26599570",
    Customer_Name: "Melissa Ortiz",
    Date: "May 25, 2025",
    Amount: "$116",
    Payment_Type: "Credit Card",
    Status: orderStatus.New_Order,
  },
  {
    Order_ID: "46343794",
    Customer_Name: "Elizabeth Moore",
    Date: "Aug 20, 2024",
    Amount: "$283",
    Payment_Type: "Cash",
    Status: orderStatus.Cancelled,
  },
  {
    Order_ID: "78561632",
    Customer_Name: "Angela Perez",
    Date: "Oct 04, 2024",
    Amount: "$350",
    Payment_Type: "PayPal",
    Status: orderStatus.New_Order,
  },
  {
    Order_ID: "58374702",
    Customer_Name: "Andrew Stewart",
    Date: "Mar 10, 2025",
    Amount: "$64",
    Payment_Type: "Cash",
    Status: orderStatus.Inprocess,
  },
  {
    Order_ID: "62355398",
    Customer_Name: "Patricia Harris",
    Date: "Jul 06, 2024",
    Amount: "$182",
    Payment_Type: "Cash",
    Status: orderStatus.Completed,
  },
  {
    Order_ID: "71319922",
    Customer_Name: "Michael Russell",
    Date: "Dec 21, 2024",
    Amount: "$237",
    Payment_Type: "PayPal",
    Status: orderStatus.New_Order,
  },
  {
    Order_ID: "87364612",
    Customer_Name: "Ashley Wells",
    Date: "Jan 24, 2025",
    Amount: "$298",
    Payment_Type: "Bank Transfer",
    Status: orderStatus.Cancelled,
  },
  {
    Order_ID: "94781456",
    Customer_Name: "Timothy Harris",
    Date: "May 23, 2025",
    Amount: "$470",
    Payment_Type: "Bank Transfer",
    Status: orderStatus.Inprocess,
  },
  {
    Order_ID: "37419127",
    Customer_Name: "Emily Johnson",
    Date: "Apr 08, 2025",
    Amount: "$197",
    Payment_Type: "Credit Card",
    Status: orderStatus.New_Order,
  },
  {
    Order_ID: "32105172",
    Customer_Name: "Gregory Green",
    Date: "Jun 30, 2024",
    Amount: "$88",
    Payment_Type: "PayPal",
    Status: orderStatus.Inprocess,
  },
  {
    Order_ID: "27089341",
    Customer_Name: "Jennifer Smith",
    Date: "Mar 18, 2025",
    Amount: "$421",
    Payment_Type: "Credit Card",
    Status: orderStatus.Completed,
  },
  {
    Order_ID: "10347219",
    Customer_Name: "Robert Martinez",
    Date: "Sep 07, 2024",
    Amount: "$77",
    Payment_Type: "Cash",
    Status: orderStatus.Inprocess,
  },
  {
    Order_ID: "50985460",
    Customer_Name: "Sarah Lee",
    Date: "Nov 28, 2024",
    Amount: "$214",
    Payment_Type: "Bank Transfer",
    Status: orderStatus.New_Order,
  },
  {
    Order_ID: "94063287",
    Customer_Name: "William Clark",
    Date: "Aug 15, 2024",
    Amount: "$303",
    Payment_Type: "Credit Card",
    Status: orderStatus.Completed,
  },
  {
    Order_ID: "75420986",
    Customer_Name: "Megan Turner",
    Date: "Dec 14, 2024",
    Amount: "$120",
    Payment_Type: "Credit Card",
    Status: orderStatus.New_Order,
  },
  {
    Order_ID: "69873210",
    Customer_Name: "Matthew Edwards",
    Date: "Oct 29, 2024",
    Amount: "$267",
    Payment_Type: "Bank Transfer",
    Status: orderStatus.Completed,
  },
  {
    Order_ID: "41230577",
    Customer_Name: "Daniel Campbell",
    Date: "Jul 21, 2024",
    Amount: "$336",
    Payment_Type: "Cash",
    Status: orderStatus.Inprocess,
  },
  {
    Order_ID: "13782459",
    Customer_Name: "Lisa Adams",
    Date: "May 09, 2025",
    Amount: "$284",
    Payment_Type: "Bank Transfer",
    Status: orderStatus.Completed,
  },
  {
    Order_ID: "32874291",
    Customer_Name: "Joshua Lewis",
    Date: "Jan 13, 2025",
    Amount: "$80",
    Payment_Type: "PayPal",
    Status: orderStatus.New_Order,
  },
  {
    Order_ID: "54821907",
    Customer_Name: "Rebecca Hall",
    Date: "Feb 27, 2025",
    Amount: "$158",
    Payment_Type: "Credit Card",
    Status: orderStatus.Inprocess,
  },
  {
    Order_ID: "86290314",
    Customer_Name: "Christopher Walker",
    Date: "Apr 15, 2025",
    Amount: "$491",
    Payment_Type: "PayPal",
    Status: orderStatus.Completed,
  },
  {
    Order_ID: "29510348",
    Customer_Name: "Amanda Allen",
    Date: "Oct 11, 2024",
    Amount: "$73",
    Payment_Type: "Cash",
    Status: orderStatus.Inprocess,
  },
  {
    Order_ID: "84570639",
    Customer_Name: "Justin Scott",
    Date: "Jul 27, 2024",
    Amount: "$238",
    Payment_Type: "PayPal",
    Status: orderStatus.New_Order,
  },
  {
    Order_ID: "18962045",
    Customer_Name: "Deborah White",
    Date: "Feb 17, 2025",
    Amount: "$413",
    Payment_Type: "Bank Transfer",
    Status: orderStatus.Cancelled,
  },
  {
    Order_ID: "51763092",
    Customer_Name: "Jonathan Young",
    Date: "Mar 31, 2025",
    Amount: "$94",
    Payment_Type: "Credit Card",
    Status: orderStatus.New_Order,
  },
  {
    Order_ID: "20391874",
    Customer_Name: "Brandon King",
    Date: "Aug 04, 2024",
    Amount: "$153",
    Payment_Type: "Cash",
    Status: orderStatus.Completed,
  },
  {
    Order_ID: "95072138",
    Customer_Name: "Linda Hernandez",
    Date: "Nov 05, 2024",
    Amount: "$212",
    Payment_Type: "PayPal",
    Status: orderStatus.Inprocess,
  },
  {
    Order_ID: "74810329",
    Customer_Name: "Joshua Baker",
    Date: "Dec 09, 2024",
    Amount: "$261",
    Payment_Type: "Credit Card",
    Status: orderStatus.New_Order,
  },
  {
    Order_ID: "63109284",
    Customer_Name: "Steven Allen",
    Date: "Sep 23, 2024",
    Amount: "$479",
    Payment_Type: "Bank Transfer",
    Status: orderStatus.Cancelled,
  },
  {
    Order_ID: "28130746",
    Customer_Name: "Mary Ramirez",
    Date: "Jan 20, 2025",
    Amount: "$345",
    Payment_Type: "Cash",
    Status: orderStatus.Inprocess,
  },
  {
    Order_ID: "54078132",
    Customer_Name: "Mark Roberts",
    Date: "Apr 27, 2025",
    Amount: "$72",
    Payment_Type: "Cash",
    Status: orderStatus.New_Order,
  },
  {
    Order_ID: "61023948",
    Customer_Name: "Barbara Lewis",
    Date: "May 03, 2025",
    Amount: "$285",
    Payment_Type: "Bank Transfer",
    Status: orderStatus.Inprocess,
  },
  {
    Order_ID: "39812704",
    Customer_Name: "Paul Hill",
    Date: "Jun 18, 2024",
    Amount: "$191",
    Payment_Type: "Credit Card",
    Status: orderStatus.Inprocess,
  },
  {
    Order_ID: "89721560",
    Customer_Name: "Elizabeth Scott",
    Date: "Sep 30, 2024",
    Amount: "$463",
    Payment_Type: "Cash",
    Status: orderStatus.New_Order,
  },
  {
    Order_ID: "53180497",
    Customer_Name: "Brian White",
    Date: "Mar 06, 2025",
    Amount: "$211",
    Payment_Type: "Bank Transfer",
    Status: orderStatus.Inprocess,
  },
  {
    Order_ID: "81273605",
    Customer_Name: "Susan Nelson",
    Date: "Jul 17, 2024",
    Amount: "$171",
    Payment_Type: "Credit Card",
    Status: orderStatus.Completed,
  },
  {
    Order_ID: "12587963",
    Customer_Name: "Ronald Harris",
    Date: "Aug 27, 2024",
    Amount: "$442",
    Payment_Type: "Cash",
    Status: orderStatus.Cancelled,
  },
  {
    Order_ID: "96108253",
    Customer_Name: "Karen Thompson",
    Date: "Oct 16, 2024",
    Amount: "$354",
    Payment_Type: "PayPal",
    Status: orderStatus.New_Order,
  },
  {
    Order_ID: "38517092",
    Customer_Name: "Edward Martinez",
    Date: "Feb 09, 2025",
    Amount: "$203",
    Payment_Type: "Cash",
    Status: orderStatus.Completed,
  },
  {
    Order_ID: "54920817",
    Customer_Name: "Jessica Lopez",
    Date: "Jan 01, 2025",
    Amount: "$105",
    Payment_Type: "PayPal",
    Status: orderStatus.Inprocess,
  },
  {
    Order_ID: "73840192",
    Customer_Name: "Patricia Gonzalez",
    Date: "Apr 20, 2025",
    Amount: "$149",
    Payment_Type: "Credit Card",
    Status: orderStatus.New_Order,
  },
  {
    Order_ID: "89371205",
    Customer_Name: "George Perez",
    Date: "Nov 19, 2024",
    Amount: "$367",
    Payment_Type: "Cash",
    Status: orderStatus.Inprocess,
  },
  {
    Order_ID: "72093158",
    Customer_Name: "Thomas Mitchell",
    Date: "Aug 10, 2024",
    Amount: "$495",
    Payment_Type: "Credit Card",
    Status: orderStatus.Cancelled,
  },
  {
    Order_ID: "31278054",
    Customer_Name: "Charles Carter",
    Date: "May 19, 2025",
    Amount: "$174",
    Payment_Type: "Bank Transfer",
    Status: orderStatus.Completed,
  },
];
