export enum employeeStatus {
  Active = "Active",
  Inactive = "Inactive",
}

export interface EmployeeTableData {
  EmployeeID: string;
  EmployeeName: string;
  EmailAddress: string;
  PhoneNumber: string;
  Status: employeeStatus;
}

export const employeeData = [
  {
    EmployeeID: "201",
    EmployeeName: "Matthew Jones",
    EmailAddress: "matthew.jones@demo.com",
    PhoneNumber: "(805) 555-9637",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "202",
    EmployeeName: "Thomas Miller",
    EmailAddress: "thomas.miller@demo.com",
    PhoneNumber: "(237) 555-3716",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "203",
    EmployeeName: "Lisa Robinson",
    EmailAddress: "lisa.robinson@demo.com",
    PhoneNumber: "(347) 555-6686",
    Status: employeeStatus.Active,
  },
  {
    EmployeeID: "204",
    EmployeeName: "Joshua White",
    EmailAddress: "joshua.white@demo.com",
    PhoneNumber: "(863) 555-8729",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "205",
    EmployeeName: "Kevin Scott",
    EmailAddress: "kevin.scott@demo.com",
    PhoneNumber: "(552) 555-2831",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "206",
    EmployeeName: "Michael Adams",
    EmailAddress: "michael.adams@demo.com",
    PhoneNumber: "(294) 555-7683",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "207",
    EmployeeName: "Susan Hall",
    EmailAddress: "susan.hall@demo.com",
    PhoneNumber: "(641) 555-9792",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "208",
    EmployeeName: "David Moore",
    EmailAddress: "david.moore@demo.com",
    PhoneNumber: "(939) 555-2025",
    Status: employeeStatus.Active,
  },
  {
    EmployeeID: "209",
    EmployeeName: "Richard Nguyen",
    EmailAddress: "richard.nguyen@demo.com",
    PhoneNumber: "(678) 555-5861",
    Status: employeeStatus.Active,
  },
  {
    EmployeeID: "210",
    EmployeeName: "Mary Green",
    EmailAddress: "mary.green@demo.com",
    PhoneNumber: "(454) 555-1972",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "211",
    EmployeeName: "Carol Moore",
    EmailAddress: "carol.moore@demo.com",
    PhoneNumber: "(264) 555-7533",
    Status: employeeStatus.Active,
  },
  {
    EmployeeID: "212",
    EmployeeName: "Ronald Hill",
    EmailAddress: "ronald.hill@demo.com",
    PhoneNumber: "(471) 555-3200",
    Status: employeeStatus.Active,
  },
  {
    EmployeeID: "213",
    EmployeeName: "Margaret Hall",
    EmailAddress: "margaret.hall@demo.com",
    PhoneNumber: "(839) 555-1955",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "214",
    EmployeeName: "James Wilson",
    EmailAddress: "james.wilson@demo.com",
    PhoneNumber: "(799) 555-9176",
    Status: employeeStatus.Active,
  },
  {
    EmployeeID: "215",
    EmployeeName: "Michael Thomas",
    EmailAddress: "michael.thomas@demo.com",
    PhoneNumber: "(267) 555-4779",
    Status: employeeStatus.Active,
  },
  {
    EmployeeID: "216",
    EmployeeName: "John Richards",
    EmailAddress: "john.richards@demo.com",
    PhoneNumber: "(561) 555-5344",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "217",
    EmployeeName: "Patricia Rivera",
    EmailAddress: "patricia.rivera@demo.com",
    PhoneNumber: "(386) 555-6531",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "218",
    EmployeeName: "Linda Williams",
    EmailAddress: "linda.williams@demo.com",
    PhoneNumber: "(418) 555-3492",
    Status: employeeStatus.Active,
  },
  {
    EmployeeID: "219",
    EmployeeName: "Matthew Young",
    EmailAddress: "matthew.young@demo.com",
    PhoneNumber: "(296) 555-8808",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "220",
    EmployeeName: "Donna Harris",
    EmailAddress: "donna.harris@demo.com",
    PhoneNumber: "(816) 555-5646",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "221",
    EmployeeName: "Jennifer Lee",
    EmailAddress: "jennifer.lee@demo.com",
    PhoneNumber: "(881) 555-9166",
    Status: employeeStatus.Active,
  },
  {
    EmployeeID: "222",
    EmployeeName: "Robert Green",
    EmailAddress: "robert.green@demo.com",
    PhoneNumber: "(254) 555-2661",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "223",
    EmployeeName: "Lisa Wright",
    EmailAddress: "lisa.wright@demo.com",
    PhoneNumber: "(941) 555-9692",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "224",
    EmployeeName: "Charles Lewis",
    EmailAddress: "charles.lewis@demo.com",
    PhoneNumber: "(869) 555-4192",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "225",
    EmployeeName: "John Scott",
    EmailAddress: "john.scott@demo.com",
    PhoneNumber: "(509) 555-4182",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "226",
    EmployeeName: "Patricia Moore",
    EmailAddress: "patricia.moore@demo.com",
    PhoneNumber: "(721) 555-2963",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "227",
    EmployeeName: "William Rivera",
    EmailAddress: "william.rivera@demo.com",
    PhoneNumber: "(636) 555-4227",
    Status: employeeStatus.Active,
  },
  {
    EmployeeID: "228",
    EmployeeName: "Leslie Garcia",
    EmailAddress: "leslie.garcia@demo.com",
    PhoneNumber: "(389) 555-1685",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "229",
    EmployeeName: "Patricia Hill",
    EmailAddress: "patricia.hill@demo.com",
    PhoneNumber: "(690) 555-4111",
    Status: employeeStatus.Active,
  },
  {
    EmployeeID: "230",
    EmployeeName: "Maria Baker",
    EmailAddress: "maria.baker@demo.com",
    PhoneNumber: "(886) 555-1928",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "231",
    EmployeeName: "Esther Wright",
    EmailAddress: "esther.wright@demo.com",
    PhoneNumber: "(836) 555-2719",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "232",
    EmployeeName: "Brooklyn Wilson",
    EmailAddress: "brooklyn.wilson@demo.com",
    PhoneNumber: "(438) 555-8133",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "233",
    EmployeeName: "Michael Rodriguez",
    EmailAddress: "michael.rodriguez@demo.com",
    PhoneNumber: "(540) 555-7126",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "234",
    EmployeeName: "Richard Harris",
    EmailAddress: "richard.harris@demo.com",
    PhoneNumber: "(943) 555-7024",
    Status: employeeStatus.Active,
  },
  {
    EmployeeID: "235",
    EmployeeName: "John Torres",
    EmailAddress: "john.torres@demo.com",
    PhoneNumber: "(620) 555-2522",
    Status: employeeStatus.Active,
  },
  {
    EmployeeID: "236",
    EmployeeName: "John Jackson",
    EmailAddress: "john.jackson@demo.com",
    PhoneNumber: "(758) 555-4439",
    Status: employeeStatus.Active,
  },
  {
    EmployeeID: "237",
    EmployeeName: "Michael White",
    EmailAddress: "michael.white@demo.com",
    PhoneNumber: "(302) 555-5415",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "238",
    EmployeeName: "Helen Martin",
    EmailAddress: "helen.martin@demo.com",
    PhoneNumber: "(370) 555-2441",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "239",
    EmployeeName: "Steven Jackson",
    EmailAddress: "steven.jackson@demo.com",
    PhoneNumber: "(838) 555-9117",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "240",
    EmployeeName: "Mary Rivera",
    EmailAddress: "mary.rivera@demo.com",
    PhoneNumber: "(797) 555-8249",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "241",
    EmployeeName: "Jennifer Moore",
    EmailAddress: "jennifer.moore@demo.com",
    PhoneNumber: "(581) 555-1168",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "242",
    EmployeeName: "Linda Williams",
    EmailAddress: "linda.williams@demo.com",
    PhoneNumber: "(988) 555-9410",
    Status: employeeStatus.Active,
  },
  {
    EmployeeID: "243",
    EmployeeName: "Thomas Scott",
    EmailAddress: "thomas.scott@demo.com",
    PhoneNumber: "(478) 555-4935",
    Status: employeeStatus.Active,
  },
  {
    EmployeeID: "244",
    EmployeeName: "Dianne Webb",
    EmailAddress: "dianne.webb@demo.com",
    PhoneNumber: "(698) 555-9515",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "245",
    EmployeeName: "Sharon Thompson",
    EmailAddress: "sharon.thompson@demo.com",
    PhoneNumber: "(437) 555-2326",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "246",
    EmployeeName: "Elizabeth Rivera",
    EmailAddress: "elizabeth.rivera@demo.com",
    PhoneNumber: "(370) 555-8857",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "247",
    EmployeeName: "Sharon Williams",
    EmailAddress: "sharon.williams@demo.com",
    PhoneNumber: "(909) 555-9520",
    Status: employeeStatus.Inactive,
  },
  {
    EmployeeID: "248",
    EmployeeName: "Donald Campbell",
    EmailAddress: "donald.campbell@demo.com",
    PhoneNumber: "(880) 555-7874",
    Status: employeeStatus.Active,
  },
  {
    EmployeeID: "249",
    EmployeeName: "Betty Wilson",
    EmailAddress: "betty.wilson@demo.com",
    PhoneNumber: "(971) 555-5349",
    Status: employeeStatus.Active,
  },
  {
    EmployeeID: "250",
    EmployeeName: "Charles Adams",
    EmailAddress: "charles.adams@demo.com",
    PhoneNumber: "(904) 555-3030",
    Status: employeeStatus.Active,
  },
];
